package fe

/*
File automatically generated by the ictiobus compiler. DO NOT EDIT. This was
created by invoking ictiobus with the following command:

    ictcc --slr -l TQTextExpansion -v 1.0 -d tte --ir github.com/dekarrin/tunaq/tunascript/syntax.ExpansionAST --hooks ./tunascript/syntax --hooks-table ExpHooksTable --dest ./tunascript/expfe tunascript/expansion.md --sim-off
*/

import (
	"github.com/dekarrin/ictiobus"
	"github.com/dekarrin/ictiobus/trans"

	"fmt"
	"strings"
)

// SDTS returns the generated ictiobus syntax-directed translation scheme for
// TQTextExpansion.
func SDTS() trans.SDTS {
	sdts := ictiobus.NewSDTS()

	sdtsBindTCExpansion(sdts)

	return sdts
}

func sdtsBindTCExpansion(sdts trans.SDTS) {
	var err error
	err = sdts.Bind(
		"EXPANSION", []string{"BLOCKS"},
		"ast",
		"test_const",
		nil,
	)
	if err != nil {
		prodStr := strings.Join([]string{"BLOCKS"}, " ")
		panic(fmt.Sprintf("binding %s -> [%s]: %s", "EXPANSION", prodStr, err.Error()))
	}
}
